image: axonasif/workspace-vnc:latest

tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
      curl -sS https://getcomposer.org/installer | php

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - ms-azuretools.vscode-docker
    - sonarsource.sonarlint-vscode
