version: '3'

services:

  php:
    build: ./docker/php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
    restart: unless-stopped

  db:
    build: ./docker/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=webrage_webrage
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  phpmyadmin:
    build: ./docker/phpmyadmin
    depends_on:
      - db
    ports:
      - "8001:80"
    restart: "no"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret

volumes:
  sql: