version: '3'

services:

  php:
    build: ./docker/php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
    networks:
      fixed_ip:
        ipv4_address: 109.71.54.18
        # ipv4_address: 172.28.1.10

  db:
    build: ./docker/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=webrage_webrage
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      fixed_ip:
        # ipv4_address: 145.53.225.236
        # ipv4_address: 172.28.1.2

  phpmyadmin:
    build: ./docker/phpmyadmin
    depends_on:
      - db
    ports:
      - "8001:80"
    restart: "no"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      fixed_ip:
        # ipv4_address: 145.53.225.237
        # ipv4_address: 172.28.1.3

volumes:
  sql:

networks:
  fixed_ip:
    ipam:
      driver: default
      config:
        #  - subnet: 145.53.0.0/16
         - subnet: 109.71.54.0/16
           gateway: 109.71.54.1
